In [18]:
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
from datetime import date

In [19]:
data = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\EmployeeDataToClean.csv" , encoding = "ISO-8859-1")

In [13]:
data.head(5)

,EmployeeID,NationalIDNumber,LoginID,Title,PhoneNumber,BirthDate,MaritalStatus,Gender,HireDate,Dept,Salary,Job Grade,CurrentFlag,rowguid
0,1,14417807,adventure-works\guy1,Gustavo Achong,9.257522e+09,21-02-1986 00:00,M,M,02-02-2013 00:00,Sales,2295.0,Admin,-1,{AAE1D04A-C237-4974-B4D5-935247737718}
1,2,253022876,adventure-works\kevin0,Catherine Abel,9.235868e+09,12-03-1991 00:00,S,M,31-08-2013 00:00,Sales,962.0,Management,-1,{1B480240-95C0-410F-A717-EB29943C8886}
2,3,509647174,NaN,Kim Abercrombie,9.416422e+09,21-09-1978 00:00,M,M,16-06-2014 00:00,Finance,4006.0,Admin,-1,{9BBBFB2C-EFBB-4217-9AB7-F97689328841}
3,4,112457891,NaN,Humberto Acevedo,8.800042e+09,01-11-1978 00:00,S,M,10-07-2014 00:00,Logistics,4547.0,Admin,-1,{59747955-87B8-443F-8ED4-F8AD3AFDF3A9}
4,5,480168528,NaN,Pilar Ackerman,NaN,07-06-1963 00:00,M,M,16-07-2014 00:00,Human Resource,1932.0,Admin,-1,{1D955171-E773-4FAD-8382-40FD898D5D4D}

In [20]:
def phn_masking(a):
    a = str(a)
    if a == '0':
        return "XXXXXXXXXX"
    else:
        result = a[0:3] + "XXXX" + a[-2:]
    return result

In [21]:
def f_materialstatus(a):
    if a == 'M':
        return 1
    else:
        return 0

In [22]:
def f_genderstatus(a):
    if a == 'M':
        return 1
    else:
        return 0

In [23]:
# data Cleaning Steps
data['PhoneNumber'] = data['PhoneNumber'].fillna(0000000000)
data['PhoneNumber'] = data['PhoneNumber'].astype("object")  # here decimal values will come to overcome this we use int64 thpe
data['PhoneNumber'] = data['PhoneNumber'].astype("int64")   # here warnings are coming to overcome this keep the import warnings syntax
data['PhoneNumber'] = data['PhoneNumber'].apply(phn_masking)
data["Is_Married"] = data['MaritalStatus'].apply(f_materialstatus)
data["Is_Male"] = data['Gender'].apply(f_genderstatus)
data = data.drop(["NationalIDNumber","LoginID","MaritalStatus", "Gender", "CurrentFlag" , "rowguid"] , axis = 1)
data["Salary"] = data["Salary"].fillna(data["Salary"].mean())
data['Dept']  = data['Dept'].str.capitalize()
data['BirthDate'] = pd.to_datetime(data['BirthDate'])
#data['HireDate'] = pd.to_datetime(data['HireDate'])
data['HireDate'] = pd.to_datetime(data['HireDate'], errors='coerce')
data['Age'] = date.today().year - data['BirthDate'].dt.year

In [24]:
data.head(5)

,EmployeeID,Title,PhoneNumber,BirthDate,HireDate,Dept,Salary,Job Grade,Is_Married,Is_Male,Age
0,1,Gustavo Achong,925XXXX51,1986-02-21,2013-02-02,Sales,2295.0,Admin,1,1,40
1,2,Catherine Abel,923XXXX60,1991-03-12,NaT,Sales,962.0,Management,0,1,35
2,3,Kim Abercrombie,941XXXX59,1978-09-21,NaT,Finance,4006.0,Admin,1,1,48
3,4,Humberto Acevedo,880XXXX25,1978-11-01,2014-10-07,Logistics,4547.0,Admin,0,1,48
4,5,Pilar Ackerman,XXXXXXXXXX,1963-06-07,NaT,Human resource,1932.0,Admin,1,1,63