In [ ]:
# int/float/str/bool --- Direct datatype

In [ ]:
# we dont have direct datatype for date --> we have to use thrugh library

In [28]:
import math
import scipy
import pandas as pd
import warnings
import numpy
import datetime  # date and date functions

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
from datetime import date

In [5]:
date.today()

datetime.date(2026, 4, 29)

In [8]:
x = date.today()

In [9]:
type(x)

datetime.date

In [11]:
print(x) # yyyy-mm-dd

2026-04-29

In [12]:
x.day

29

In [13]:
x.month

4

In [14]:
x.year

2026

In [19]:
x.strftime("%A")

'Wednesday'

In [20]:
x.strftime("%a")

'Wed'

In [21]:
x.strftime("%b")

'Apr'

In [22]:
x.strftime("%B")

'April'

In [23]:
x.strftime("%j")

'119'

In [ ]:
# use case

In [29]:
data = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\Sample_Store_1.csv" , encoding = "ISO-8859-1")

In [30]:
data.head(5)

,RowID,OrderID,OrderDate,ShipDate,ShipMode,CustomerID,CustomerName,Segment,Country,City,...,PostalCode,Region,ProductID,Category,Sub_Category,ProductName,Sales,Quantity,Discount,Profit
0,2698,CA-2016-145317,18-03-2016,23-03-2016,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,...,32216.0,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784
1,6827,CA-2018-118689,02-10-2018,09-10-2018,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905.0,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760
2,8154,CA-2019-140151,23-03-2019,25-03-2019,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115.0,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808
3,2624,CA-2019-127180,22-10-2019,24-10-2019,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,...,10024.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888
4,4191,CA-2019-166709,17-11-2019,22-11-2019,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,19711.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856

In [31]:
data.dtypes

RowID             int64
OrderID          object
OrderDate        object
ShipDate         object
ShipMode         object
CustomerID       object
CustomerName     object
Segment          object
Country          object
City             object
State            object
PostalCode      float64
Region           object
ProductID        object
Category         object
Sub_Category     object
ProductName      object
Sales           float64
Quantity          int64
Discount        float64
Profit          float64
dtype: object

In [32]:
# OrderDate  is object but it is not date datatype

In [33]:
data = data[["OrderDate" , "Segment" , "Region" , "Sub_Category" ,"Sales" ,"Profit"]]

In [34]:
data.head(5)

    OrderDate      Segment   Region Sub_Category      Sales     Profit
0  18-03-2016  Home Office    South     Machines  22638.480 -1811.0784
1  02-10-2018    Corporate  Central      Copiers  17499.950  8399.9760
2  23-03-2019     Consumer     West      Copiers  13999.960  6719.9808
3  22-10-2019  Home Office     East      Copiers  11199.968  3919.9888
4  17-11-2019     Consumer     East      Copiers  10499.970  5039.9856

In [36]:
# (sun to sat) which day has highest sales

In [37]:
data.dtypes

OrderDate        object
Segment          object
Region           object
Sub_Category     object
Sales           float64
Profit          float64
dtype: object

In [ ]:
# step 1 - Change the data types to date object to date time

In [38]:
data['OrderDate'] = pd.to_datetime(data['OrderDate'])

In [39]:
data.dtypes

OrderDate       datetime64[ns]
Segment                 object
Region                  object
Sub_Category            object
Sales                  float64
Profit                 float64
dtype: object

In [44]:
data['Year'] = data['OrderDate'].dt.year
data['Month'] = data['OrderDate'].dt.month
data['day'] = data['OrderDate'].dt.day

In [42]:
data.dtypes

OrderDate       datetime64[ns]
Segment                 object
Region                  object
Sub_Category            object
Sales                  float64
Profit                 float64
Year                     int32
dtype: object

In [45]:
data.head(3)

,OrderDate,Segment,Region,Sub_Category,Sales,Profit,Year,Month,day
0,2016-03-18,Home Office,South,Machines,22638.48,-1811.0784,2016,3,18
1,2018-10-02,Corporate,Central,Copiers,17499.95,8399.9760,2018,10,2
2,2019-03-23,Consumer,West,Copiers,13999.96,6719.9808,2019,3,23

In [46]:
data['DayName'] = data['OrderDate'].dt.day_name()

In [47]:
data.head(3)

,OrderDate,Segment,Region,Sub_Category,Sales,Profit,Year,Month,day,DayName
0,2016-03-18,Home Office,South,Machines,22638.48,-1811.0784,2016,3,18,Friday
1,2018-10-02,Corporate,Central,Copiers,17499.95,8399.9760,2018,10,2,Tuesday
2,2019-03-23,Consumer,West,Copiers,13999.96,6719.9808,2019,3,23,Saturday

In [48]:
data.groupby("DayName")[["Sales"]].sum().reset_index().sort_values("Sales" , ascending = False)

     DayName        Sales
1     Monday  396014.2259
6  Wednesday  392859.0138
5    Tuesday  373021.0407
3     Sunday  341391.5781
4   Thursday  298677.7432
2   Saturday  288238.6406
0     Friday  206998.6180