In [1]:
import pandas as pd

In [5]:
emp = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Emp1.csv" , encoding = "ISO-8859-1")

In [3]:
training = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Training1.csv" , encoding = "ISO-8859-1")

In [6]:
emp.head(10)

,EmployeeID,ManagerID,Title,MaritalStatus,Gender,HireDate,Dept,JobGrade
0,1,16,Gustavo Achong,M,M,02-02-2013 00:00,Sales,Admin
1,2,6,Catherine Abel,S,M,31-08-2013 00:00,Sales,Management
2,3,12,Kim Abercrombie,M,M,16-06-2014 00:00,Finance,Admin
3,4,3,Humberto Acevedo,S,M,10-07-2014 00:00,Logistics,Admin
4,5,263,Pilar Ackerman,M,M,16-07-2014 00:00,Human Resource,Admin
5,6,109,Frances Adams,S,M,25-07-2014 00:00,Sales,Management
6,7,21,Margaret Smith,S,F,31-07-2014 00:00,Sales,Operations
7,8,185,Carla Adams,M,F,11-08-2014 00:00,Finance,Management
8,9,3,Jay Adams,M,F,11-08-2014 00:00,Finance,Admin
9,10,185,Ronald Adina,S,M,12-08-2014 00:00,Logistics,Admin

In [7]:
training.head(5)

,Start Date,Course Code,Course Name,Employee_ID,Cost,Supplier
0,18-09-2015,1,Communication Workshop,1,1300,Communication Experts
1,18-09-2015,1,Communication Workshop,4,1300,Communication Experts
2,18-09-2015,1,Communication Workshop,25,1300,Communication Experts
3,18-09-2015,1,Communication Workshop,33,1300,Communication Experts
4,18-09-2015,1,Communication Workshop,44,1300,Communication Experts

In [ ]:
# I want to see which emp had spent max amount for training (cost)

In [10]:
training.groupby("Employee_ID")[["Cost"]].sum().reset_index().sort_values("Cost" , ascending = False).head(5)

    Employee_ID   Cost
11           12  47850
13           14  38150
27           28  36000
5             6  31500
20           21  29400

In [ ]:
# joins with groupby

In [12]:
result = pd.merge(emp, training, left_on = "EmployeeID", right_on = "Employee_ID", how = "inner")

In [13]:
result.shape

(419, 14)

In [14]:
result.columns

Index(['EmployeeID', 'ManagerID', 'Title', 'MaritalStatus', 'Gender',
       'HireDate', 'Dept', 'JobGrade', 'Start Date', 'Course Code',
       'Course Name', 'Employee_ID', 'Cost', 'Supplier'],
      dtype='object')

In [15]:
result.groupby("Title")[["Cost"]].sum().reset_index().sort_values("Cost" , ascending = False).head(10)

               Title   Cost
16     James Aguilar  47850
10  François Ferrier  38150
4      Cecil Allison  36000
9      Frances Adams  31500
11  Gregory Alderson  29400
22    Kyley Arbelaez  29300
25    Margaret Smith  28300
28    Maxwell Amland  27450
19         John Ault  25500
21         Kim Akers  25050

In [19]:
pd.merge(emp, training, left_on = "EmployeeID", right_on = "Employee_ID", how = "inner") \
    .groupby("Title")[["Cost"]].sum().reset_index() \
    .query("Cost > 30000") \
    .sort_values("Cost" , ascending = False)

               Title   Cost
16     James Aguilar  47850
10  François Ferrier  38150
4      Cecil Allison  36000
9      Frances Adams  31500