In [3]:
import pandas as pd

In [1]:
# without classes

In [4]:
cust_data = pd.read_excel("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\Cust_Data.xlsx")

In [6]:
bike_data = pd.read_excel("C:\\Users\\DELL\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\Bike_Data.xlsx")

In [7]:
car_data = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\Car_Data.csv")

In [8]:
cust_data.head(5)

   CustID  CustName   CustLoc  CustAge
0     1.0     Kiran      Pune     29.0
1     1.0     Kiran      Pune     29.0
2     2.0   Sathish  Maldives     30.0
3     3.0    Eshwar    Mumbai     34.0
4     5.0  Santhosh  Maldives     30.0

In [9]:
cust_data.dtypes

CustID      float64
CustName     object
CustLoc      object
CustAge     float64
dtype: object

In [10]:
cust_data.shape

(8, 4)

In [15]:
cust_data.shape[0]

8

In [16]:
cust_data.shape[1]

4

In [11]:
cust_data.isna().sum()

CustID      1
CustName    2
CustLoc     1
CustAge     2
dtype: int64

In [13]:
cust_data.isna().sum() / cust_data.shape[0]

CustID      0.125
CustName    0.250
CustLoc     0.125
CustAge     0.250
dtype: float64

In [14]:
list(cust_data.columns)

['CustID', 'CustName', 'CustLoc', 'CustAge']

In [ ]:
# with class

In [59]:
class data_cleaning:
    def __init__(self,data):
        self.data = data
    def volume_chk(self):
        return self.data.shape
    def sample_data(self):
        return self.data.head(5)
    def data_typed(self):
        return self.data.dtypes
    def row_count(self):
        print("The No of rows in given data set:" , self.data.shape[0])
    def column_count(self):
        print("The No of columns in given data set:" , self.data.shape[1])
    def missing_values(self):
        return self.data.isna().sum()
    def missing_value_percentage(self):
        return (self.data.isna().sum() / self.data.shape[0]) * 100
    def column_list(self):
        return list(self.data.columns)

In [60]:
d1 = data_cleaning(cust_data)

In [61]:
d1.column_count()

The No of columns in given data set: 4

In [62]:
d1.volume_chk()

(8, 4)

In [63]:
d1.sample_data()

   CustID  CustName   CustLoc  CustAge
0     1.0     Kiran      Pune     29.0
1     1.0     Kiran      Pune     29.0
2     2.0   Sathish  Maldives     30.0
3     3.0    Eshwar    Mumbai     34.0
4     5.0  Santhosh  Maldives     30.0

In [64]:
d1.data_typed()

CustID      float64
CustName     object
CustLoc      object
CustAge     float64
dtype: object

In [65]:
d1.row_count()

The No of rows in given data set: 8

In [66]:
d1.missing_values()

CustID      1
CustName    2
CustLoc     1
CustAge     2
dtype: int64

In [67]:
d1.missing_value_percentage()

CustID      12.5
CustName    25.0
CustLoc     12.5
CustAge     25.0
dtype: float64

In [68]:
d1.column_list()

['CustID', 'CustName', 'CustLoc', 'CustAge']

In [69]:
b1 = data_cleaning(bike_data)

In [70]:
b1.column_count()

The No of columns in given data set: 11

In [71]:
b1.missing_values()

Region                 0
Country                0
Customer               0
Business Segment       0
Category               0
Model                  0
Color               5226
SalesDate              0
ListPrice              0
UnitPrice              0
OrderQty               0
dtype: int64

In [72]:
b1.column_list()

['Region',
 'Country',
 'Customer',
 'Business Segment',
 'Category',
 'Model',
 'Color',
 'SalesDate',
 'ListPrice',
 'UnitPrice',
 'OrderQty']

In [73]:
b1.data_typed()

Region                      object
Country                     object
Customer                    object
Business Segment            object
Category                    object
Model                       object
Color                       object
SalesDate           datetime64[ns]
ListPrice                  float64
UnitPrice                  float64
OrderQty                     int64
dtype: object

In [74]:
b1.missing_value_percentage()

Region              0.000000
Country             0.000000
Customer            0.000000
Business Segment    0.000000
Category            0.000000
Model               0.000000
Color               8.578464
SalesDate           0.000000
ListPrice           0.000000
UnitPrice           0.000000
OrderQty            0.000000
dtype: float64

In [75]:
b1.missing_values()

Region                 0
Country                0
Customer               0
Business Segment       0
Category               0
Model                  0
Color               5226
SalesDate              0
ListPrice              0
UnitPrice              0
OrderQty               0
dtype: int64

In [76]:
b1.row_count()

The No of rows in given data set: 60920

In [77]:
b1.sample_data()

,Region,Country,Customer,Business Segment,Category,Model,Color,SalesDate,ListPrice,UnitPrice,OrderQty
0,North America,United States,Professional Containers and Packaging Co.,Clothing,Tights,Women's Tights,Black,2018-08-22,74.99,44.99,1
1,North America,United States,Professional Containers and Packaging Co.,Clothing,Gloves,Full-Finger Gloves,Black,2018-08-17,37.99,22.79,2
2,North America,United States,Professional Containers and Packaging Co.,Bikes,Mountain Bikes,Mountain-200,Black,2018-08-14,2294.99,1229.46,1
3,North America,United States,Professional Containers and Packaging Co.,Clothing,Jerseys,Long-Sleeve Logo Jersey,Multi,2018-08-13,49.99,28.84,6
4,North America,United States,Professional Containers and Packaging Co.,Clothing,Gloves,Full-Finger Gloves,Black,2018-08-09,37.99,22.79,4

In [78]:
b1.volume_chk()

(60920, 11)

In [80]:
c1 = data_cleaning(car_data)

In [81]:
c1.column_count()

The No of columns in given data set: 9

In [82]:
c1.column_list()

['Car_Name',
 'Year',
 'Selling_Price',
 'Present_Price',
 'Kms_Driven',
 'Fuel_Type',
 'Seller_Type',
 'Transmission',
 'Car_Owner']

In [83]:
c1.data_typed()

Car_Name          object
Year               int64
Selling_Price    float64
Present_Price    float64
Kms_Driven         int64
Fuel_Type         object
Seller_Type       object
Transmission      object
Car_Owner         object
dtype: object

In [84]:
c1.missing_value_percentage()

Car_Name         0.0
Year             0.0
Selling_Price    0.0
Present_Price    0.0
Kms_Driven       0.0
Fuel_Type        0.0
Seller_Type      0.0
Transmission     0.0
Car_Owner        0.0
dtype: float64

In [85]:
c1.missing_values()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Car_Owner        0
dtype: int64

In [86]:
c1.row_count()

The No of rows in given data set: 301

In [87]:
c1.sample_data()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,1st Owner
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,1st Owner
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,1st Owner
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,2nd Owner

In [88]:
c1.volume_chk()

(301, 9)